base-path: /api
port: 3000

paths-options:
    routes: 'routes'
    events: 'events'
    middlewares: 'middlewares'

express-options:
    Name: Value
    - Name=Value

cors-options:
    origin: '*'
    options-success-code: 204
    preflight-continue: false
    max-age: null
    credentials: null
    exposed-headers:
        -
    allowed-headers:
        -
    methods:
        -
