version: '3.8'

services:
    app:
        image: bracketed/node-express:production
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        restart: always
