import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	docSidebar: [
		{ type: 'link', href: 'https://github.com/bracketed/jova.js', label: 'Jova repository' },
		{ type: 'link', href: 'https://npmjs.com/package/@bracketed/jova.js', label: 'NPM Package' },

		{
			type: 'category',
			label: 'Guide',
			items: [{ type: 'autogenerated', dirName: 'Guide' }],
			collapsed: false,
			collapsible: false,
			link: {
				type: 'doc',
				id: 'Guide/Guide',
			},
		},
		{
			type: 'category',
			label: 'Documentation',
			items: [{ type: 'autogenerated', dirName: 'Documentation' }],
			link: {
				type: 'doc',
				id: 'Documentation/index',
			},
		},
		{ type: 'doc', id: 'Contributing' },
	],
};

export default sidebars;

