export enum ContentType {
	JSON = 'application/json',
	Text = 'text/plain',
	HTML = 'text/html',
	XML = 'application/xml',
	CSV = 'text/csv',
	FormURLEncoded = 'application/x-www-form-urlencoded',
	MultipartFormData = 'multipart/form-data',
	Javascript = 'application/javascript',
	PDF = 'application/pdf',
	OctetStream = 'application/octet-stream',
	ZIP = 'application/zip',
	GIF = 'image/gif',
	JPEG = 'image/jpeg',
	PNG = 'image/png',
	SVG = 'image/svg+xml',
	Webp = 'image/webp',
	MP4 = 'video/mp4',
	MP3 = 'audio/mpeg',
	OGG = 'audio/ogg',
	WAV = 'audio/wav',
	WEBM = 'video/webm',
}
