name: Node.js Package (NPM)

on:
    workflow_dispatch:
    #push:

jobs:
    verify:
        uses: Bracketed/Workflows/.github/workflows/Version-Check.yml@main
        name: Version Check
        permissions:
            contents: write
            actions: write
        secrets:
            BRSFTWORKS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            project-name: '@bracketed/jova.js'
            checkout-depth: 2
            checkout-ref: master
            cancel-on-same: true

    test:
        needs: verify
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.0
            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: 22
            - run: npm install --force
            - run: npm run build

    publish:
        needs: [test, verify]
        uses: Bracketed/Workflows/.github/workflows/Package-Publish.yml@main
        permissions:
            contents: write
            id-token: write
            actions: write
        with:
            project-name: '@bracketed/jova.js'
            checkout-ref: master
        secrets:
            BRSFTWORKS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}

    alt-publish:
        needs: [test, verify]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4.2.0
            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: 23
                  registry-url: https://registry.npmjs.org/

            - run: sed -i 's#"@bracketed/jova.js"#"jova.js"#g' package.json
            - run: npm install --force
            - run: npm run build
            - run: npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
