name: Node.js Package (NPM)

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.0
            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: 22
            - run: npm install
            - run: npm run build:production

    publish:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4.2.0
            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/
            - run: npm install
            - run: npm run build:production
            - run: npm publish --access public --provenance
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
            - run: sed -i 's#"@bracketed/jova.js"#"jova.js"#g' package.json
            - run: npm install
            - run: npm run build:production

            - run: npm publish --access public --provenance
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
