name: Deploy Docusaurus site to GitHub Pages

on:
    push:
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22' # Use the node version that matches your project

            - name: Install dependencies
              working-directory: ./docs
              run: npm install

            - name: Build Docusaurus site
              working-directory: ./docs
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/build # The folder where the Docusaurus site is generated
