name: Version Check

on:
    workflow_dispatch:
    push:

jobs:
    VersionVerify:
        uses: Bracketed/Workflows/.github/workflows/Version-Check.yml@main
        name: Version Check
        permissions:
            contents: write
            actions: write
        secrets:
            BRSFTWORKS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            project-name: '@bracketed/jova.js'
            checkout-depth: 2
            checkout-ref: master
            workflow-runid: ${{ github.run_id }}

    runs:
        runs-on: ubuntu-latest
        name: Extras
        needs: [VersionVerify]
        steps:
            - run: echo "Hello!"
