name: Update Wiki

on:
    push:

jobs:
    update-wiki:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main repo
              uses: actions/checkout@v3

            - name: Generate TypeDoc Documentation
              run: |
                  npm install
                  npx typedoc --out docs

            - name: Checkout wiki repo
              uses: actions/checkout@v3
              with:
                  repository: Bracketed/jova.js.wiki
                  path: wiki

            - name: Sync docs folder
              run: |
                  cp -r docs/* wiki/

            - name: Commit and push changes
              run: |
                  cd wiki
                  git config user.name "github-actions"
                  git config user.email "actions@github.com"
                  git add .
                  git commit -m "Update TypeDoc documentation" || echo "No changes to commit"
                  git push
